# Generated by Django 6.0.6 on 2026-07-01 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(max_length=400, verbose_name='Descrição')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluida')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
